#!/bin/bash

echo "Give us the tools, and we will finish the job"
echo "Run Forest, Run!"

sudo apt-get update

if ! which curl
then
	sudo apt install curl
fi

if ! which python 
then
	sudo apt install python
fi


if which pip 
then 
	pip install -U pip
else
	sudo apt install python-pip

fi

cd ..

if [[ -d ./Debcrypt/ ]]
then
	cd Debcrypt
	git pull
	cd ..
else
	git clone https://github.com/BREAKTEAM/Debcrypt.git
fi

if [[ -d ./hashcat/ ]]
then
	sudo apt-get upgrade
else
	sudo apt-get install hashcat
fi

if [[ -d ./impacket/ ]]
then
	cd impacket
	git pull
	pip install . 
	cd ..
else
	git clone https://github.com/SecureAuthCorp/impacket.git
	cd impacket
	pip install .
	cd ..	
fi

cd Berg-Kit